[project]
name = "Json-convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.uv.sources]
en-core-web-sm = { path = "backend/api/en_core_web_sm-3.7.1-py3-none-any.whl" }
